### ISSUE TITLE
Running the examples has unknown import error inherit_spawn not defined

### ISSUE THREAD

**Issue by kellpossible** [bailion/puck#52]
Running either the chat or list examples has this error:

```
Error: unknown import: `lunatic::process::inherit_spawn` has not been defined
```

**Comment by teymour-aldridge** [comment]
Oops - will investigate (probably over the weekend)

**Comment by teymour-aldridge** [comment]
I suspect the problem here is that you are running Puck using the latest version of `lunatic` (at the moment it only supports 0.7 rather than 0.9. I've pushed a patch which updates the version, so hopefully this should be fixed.
